### PR TITLE
TEST

### PR DESCRIPTION
**Pull request by Gunikosamin**
This is request from user .
They will be able to select difficulty (easy/normal/hard) .

Plz sign off , if you think good ,Take.

Thanks.

Oguni

### CODE REVIEW

**Comment by PracticeStudy** [comment]
who are you?

**Comment by Gunikosamin** [comment]
I don't know ,too

**Review by PracticeStudy — COMMENTED** [review]
問題ない

**Review by PracticeStudy — APPROVED** [review]
問題ないよ

**Pull request merged**
